name=aarhus

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.datasource.username=piotr
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/test
spring.datasource.password=123

spring.cloud.stream.bindings.output.destination=orgChangeTopic
spring.cloud.stream.bindings.output.content-type=application/json
spring.cloud.stream.kafka.binder.zkNodes=kafka
spring.cloud.stream.kafka.binder.brokers=kafka

server.port=8081

spring.cloud.loadbalancer.ribbon.enabled=false
        
management.endpoints.web.exposure.include=*
management.endpoints.enabled-by-default=true

eureka.instance.preferIpAddress=true
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.client.serviceUrl.defaultZone=http://kolding:8070/eureka/

resilience4j.circuitbreaker.instances.myServiceInstance.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.myServiceInstance.slidingWindowSize=10
resilience4j.circuitbreaker.instances.myServiceInstance.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.myServiceInstance.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.myServiceInstance.failureRateThreshold=20
resilience4j.circuitbreaker.instances.myServiceInstance.waitDurationInOpenState=10000

