name=odense
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:postgresql://docker.internal:5432/test
spring.datasource.username=piotr
spring.datasource.password=123

