lala=baba
server.port=8097
unser.port=8097
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
unser.eureka=${EUREKA_URI:http://localhost:8761/eureka}
spring.application.name=serwisus
unser.name=serwisus
EUREKA_URI=http://localhost:8761/eureka
